### ISSUE TITLE
[bug] Example code not working - Unexpected error

### ISSUE THREAD

**Issue by built-by-as** [stripe/stripe-identity-react-native#72]
Lib version: `"@stripe/stripe-identity-react-native": "github:stripe/stripe-identity-react-native",`
not sure why this doesn't show 0.1.0 when doing `npm i @stripe/stripe-identity-react-native`

```
export function IdVerification() {
  const fetchOptions = async () => {
    const response = await createVerificationSession();
    console.log(response);
    return {
      sessionId: response.id,
      ephemeralKeySecret: response.client_secret,
      brandLogo: Image.resolveAssetSource(
        require('<path to logo>'),
      ),
    };
  };

  const {status, present, loading} = useStripeIdentity(fetchOptions);

  console.log(status, present, loading);
  const handlePress = useCallback(async () => {
    try {
      await present();
    } catch (error) {
      console.error(error);
    }
  }, [present]);

  return (
    <View style={{flex: 1, backgroundColor: Colors.background}}>
      <View style={{marginHorizontal: 10, alignItems: 'center'}}>
        <Button
          label="Begin Verification"
          backgroundColor="black"
          style={{marginTop: 20, width: 250}}
          enableShadow
          onPress={() => {
            handlePress();
          }}
        />
      </View>
    </View>
  );
}
```

whenever I try to start the verification, I see the sheet presented and then the error "There was an unexpected error -- try again in a few seconds". There are no logs Xcode to help diagnose the issue.

**Comment by filipac** [comment]
I have the same problem... and not sure how to debug it

**Comment by filipac** [comment]
The problem is that is seems that this library expects an ephemeral key, that is tied to a customer... but the identity verification cannot be tied to a customer. This is where the problem appears I think.
I used to pass `client_secret` from the verification session but seems that the package wants an ephemeral key.

Is there a clue on how to make that ephemeral key?

**Comment by filipac** [comment]
`Received unknown parameter: verification_session` when trying to make an ephemeral key for the verification session.

**Comment by ruben-stripe** [comment]
Hi 👋 thanks for the interest in our react native SDK! It is currently in beta and would require us to add your merchant to work, please send an email to [identity-mobile-sdk-beta@stripe.com](mailto:identity-mobile-sdk-beta@stripe.com) with your merchant information and we'll work with you to integrate the SDK.

**Comment by ccen-stripe** [comment]
Close due to inactivity

**Comment by sleekLancelot** [comment]
> (async () => {
>     try {
>       await present();
>     } catch (error) {
>       console.error(error);
>     }
>   }, [present]);

Hi, so i'm guessing it passed the beta stage right, because i am facing this error right now on iOS.
And on android the app just crashes with this error "java.lang.IllegalArgumentException: createMdcTheme requires the host context's theme to extend Theme.MaterialComponents" even after i rebuilt my devClient.
Please any advise on how to solve this?

**Comment by sleekLancelot** [comment]
> Hi 👋 thanks for the interest in our react native SDK! It is currently in beta and would require us to add your merchant to work, please send an email to [identity-mobile-sdk-beta@stripe.com](mailto:identity-mobile-sdk-beta@stripe.com) with your merchant information and we'll work with you to integrate the SDK.

Hi, so i'm guessing it passed the beta stage right, because i am facing this error right now on iOS.
And on android the app just crashes with this error "java.lang.IllegalArgumentException: createMdcTheme requires the host context's theme to extend Theme.MaterialComponents" even after i rebuilt my devClient.
Please any advise on how to solve this?

**Comment by ccen-stripe** [comment]
hi @sleekLancelot, yes now it's public and you don't need to be gated in.
Please try the latest version [0.1.8](https://github.com/stripe/stripe-identity-react-native/releases/tag/v0.1.8) and refer to the example app [here](https://github.com/stripe/stripe-identity-react-native/tree/main/example).

For the Android issue, your app needs to use material theme because material components are used to build native UI, please refer to [this](https://stripe.com/docs/identity/verify-identity-documents?platform=android&type=new-integration#set-up-material-theme) section for details.
